### ISSUE TITLE
Replace JSON data system

### ISSUE THREAD

**Issue by jrmcintyre** [jrmcintyre/lightning#12]
Could use MongoDB or a variant of SQL

**Comment by MonSpek** [comment]
In my opinion the JSON system should be replaced with a database system. There are a few structures I have commonly seen used: those being, mongoDB, mySQL, and SQLite. I currently have no understanding of any SQL based system or SQL; that being said, I do have some experience with mongoDB. Even with my lack of understanding for SQL, I think mongoDB would be better as it has a well made [browser](https://www.mongodb.com/products/compass). This browser allows us to easily view and change data from our desktops without having to go into server management systems. MongoDB is also a more accepted database system within discord bot development; and how I see it, mongoDB is less clunky. That being said, from my understanding, our best option to replace the JSON system, is to use mLab on heroku. mLab offers free mongoDB hosting with ~500mb (which should be more than fine, at least for now) on a shared server with varied RAM. In addition, if we ever wanted to upscale, we can get a paid version of the hosting. mLab has an add-on on heroku so deployment shouldn't be so hard, but I haven't looked into the deployment process.
-MonSpek
